// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAwtoM_gZjZymksCCM170ZuCuczLz2aWQI',
//     appId: '1:83897679280:web:9814272a5f32d7538bea75',
//     messagingSenderId: '83897679280',
//     projectId: 'reserveat-app',
//     authDomain: 'reserveat-app.firebaseapp.com',
//     storageBucket: 'reserveat-app.appspot.com',
//     measurementId: 'G-Q8BE3321DZ',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAUF8TWwXW_fmj1ajAcWhsWe_1sXsmj138',
//     appId: '1:83897679280:android:3c1b636724aae5b18bea75',
//     messagingSenderId: '83897679280',
//     projectId: 'reserveat-app',
//     storageBucket: 'reserveat-app.appspot.com',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAwtoM_gZjZymksCCM170ZuCuczLz2aWQI',
//     appId: '1:83897679280:web:42e850bf81b4a2778bea75',
//     messagingSenderId: '83897679280',
//     projectId: 'reserveat-app',
//     authDomain: 'reserveat-app.firebaseapp.com',
//     storageBucket: 'reserveat-app.appspot.com',
//     measurementId: 'G-8MRRDVQKWD',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB1Rg8CUd-RYiXIMF3IKSqQVa3WFoKQBwk',
//     appId: '1:83897679280:ios:637871705b45b4ef8bea75',
//     messagingSenderId: '83897679280',
//     projectId: 'reserveat-app',
//     storageBucket: 'reserveat-app.appspot.com',
//     iosBundleId: 'com.example.reserveat',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB1Rg8CUd-RYiXIMF3IKSqQVa3WFoKQBwk',
//     appId: '1:83897679280:ios:637871705b45b4ef8bea75',
//     messagingSenderId: '83897679280',
//     projectId: 'reserveat-app',
//     storageBucket: 'reserveat-app.appspot.com',
//     iosBundleId: 'com.example.reserveat',
//   );

// }